apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cicd-app-skaffold
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  cloudrun: {}
profiles:
  - name: staging
    manifests:
      rawYaml:
        - k8s/*.yaml
  - name: prod
    manifests:
      rawYaml:
        - k8s/*.yaml
